import Link from "next/link";

const operatingSignals = [
  { label: "Customers", value: "128 active", change: "+18% this month" },
  { label: "Cash position", value: "NGN 4.8m", change: "12 invoices due" },
  { label: "Team focus", value: "34 tasks", change: "8 need attention" },
];

const operatingLayers = [
  { index: "01", title: "See the business", text: "A living view of customers, cash, work, and momentum, shaped around the way your team actually operates.", tone: "from-violet-500/20 to-fuchsia-500/5" },
  { index: "02", title: "Understand the context", text: "Kora remembers the signals behind the numbers, so every recommendation has a source, a reason, and a next step.", tone: "from-fuchsia-500/20 to-rose-500/5" },
  { index: "03", title: "Move with confidence", text: "Turn insight into action without switching between disconnected tools or losing the thread of the work.", tone: "from-indigo-500/20 to-violet-500/5" },
];

const proofPoints = [
  ["One operating picture", "Customers, invoices, tasks, and payments belong to one organization-aware system."],
  ["A memory that compounds", "Every meaningful action becomes context for better decisions tomorrow."],
  ["Control stays human", "Recommendations show their source and people remain in charge of what happens next."],
];

export default function HomePage() {
  return (
    <main className="overflow-hidden bg-[#050509] text-[#f8f7ff]">
      <nav className="mx-auto flex max-w-7xl items-center justify-between px-5 py-6 sm:px-8 lg:px-10">
        <Link href="/" className="flex items-center gap-3" aria-label="Kora home"><span className="logo-mark">K</span><span><span className="block text-[0.62rem] uppercase tracking-[0.32em] text-violet-200/70">Business OS</span><span className="block text-lg font-semibold text-white">Kora</span></span></Link>
        <div className="hidden items-center gap-8 text-sm text-slate-400 md:flex"><a href="#system" className="transition hover:text-white">The system</a><a href="#workflow" className="transition hover:text-white">How it works</a><a href="#operators" className="transition hover:text-white">For operators</a></div>
        <div className="flex items-center gap-3"><Link href="/auth?mode=signin" className="hidden rounded-full px-4 py-2 text-sm text-slate-300 transition hover:text-white sm:block">Sign in</Link><Link href="/auth?mode=signup" className="rounded-full bg-violet-500 px-4 py-2.5 text-sm font-semibold text-white shadow-[0_0_28px_rgba(139,92,246,0.3)] transition hover:bg-violet-400">Start with Kora</Link></div>
      </nav>

      <section className="relative mx-auto grid min-h-[720px] max-w-7xl items-center gap-12 px-5 pb-20 pt-12 sm:px-8 lg:grid-cols-[0.9fr_1.1fr] lg:px-10 lg:pt-16">
        <div className="relative z-[1]"><p className="mb-7 flex items-center gap-3 text-[0.68rem] uppercase tracking-[0.28em] text-violet-200"><span className="h-2 w-2 rounded-full bg-fuchsia-400 shadow-[0_0_16px_#d946ef]" />The intelligence layer for real businesses</p><h1 className="max-w-3xl text-6xl font-semibold leading-[0.92] tracking-[-0.04em] text-white sm:text-7xl lg:text-[7.2rem]">Run the whole business from one clear signal.</h1><p className="mt-8 max-w-xl text-lg leading-8 text-slate-300">Kora connects the people, money, customers, and work inside your company, then gives you the context to decide what matters next.</p><div className="mt-9 flex flex-wrap items-center gap-4"><Link href="/auth?mode=signup" className="rounded-full bg-white px-6 py-3.5 text-sm font-semibold text-[#08080f] transition hover:bg-violet-100">Create your workspace <span className="ml-2">↗</span></Link><a href="#system" className="rounded-full border border-white/15 px-6 py-3.5 text-sm text-slate-200 transition hover:border-violet-300/70 hover:text-white">Explore the system</a></div><div className="mt-14 grid max-w-2xl grid-cols-3 border-y border-white/10 py-5">{operatingSignals.map((signal) => <div key={signal.label} className="pr-3"><p className="text-[0.62rem] uppercase tracking-[0.18em] text-slate-500">{signal.label}</p><p className="mt-2 text-xl font-semibold text-white">{signal.value}</p><p className="mt-1 text-xs text-violet-200/70">{signal.change}</p></div>)}</div></div>
        <div className="relative min-h-[500px] lg:min-h-[620px]"><div className="absolute right-0 top-8 h-[470px] w-[470px] rounded-full bg-violet-600/10 blur-3xl" /><div className="kora-core-stage mx-auto mt-4 lg:mt-16" aria-label="Kora intelligence core visual"><div className="kora-core-orbit kora-core-orbit-one" /><div className="kora-core-orbit kora-core-orbit-two" /><div className="kora-core"><span>K</span></div><div className="kora-core-label">Business signal / live</div></div><div className="absolute left-0 top-20 hidden w-52 border-l border-violet-400/50 pl-4 text-xs leading-5 text-slate-400 sm:block"><span className="text-violet-200">Kora is learning</span><br />Your payment cycle is tightening. Two follow-ups could unlock this week&apos;s cash position.</div><div className="absolute bottom-8 right-0 w-64 border border-white/10 bg-[#101019]/90 p-4 shadow-2xl backdrop-blur-xl"><p className="text-[0.62rem] uppercase tracking-[0.18em] text-slate-500">Next best move</p><p className="mt-3 text-sm leading-6 text-white">Follow up with 3 overdue accounts before Friday.</p><span className="mt-4 block text-xs text-fuchsia-300">Based on 12 recorded signals →</span></div><img src="https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1000&q=85" alt="Team reviewing business operations together" className="absolute bottom-0 left-8 h-44 w-64 object-cover opacity-35 grayscale" /></div>
      </section>

      <section className="border-y border-white/10 bg-[#0a0a11]" id="system"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-20 sm:px-8 lg:grid-cols-[0.7fr_1.3fr] lg:px-10 lg:py-28"><div><p className="text-[0.68rem] uppercase tracking-[0.24em] text-violet-300">The Kora system</p><h2 className="mt-5 max-w-md text-4xl font-semibold leading-tight text-white sm:text-5xl">Your business is already telling you what to do.</h2></div><div className="grid gap-0 border-t border-white/10">{operatingLayers.map((layer) => <article key={layer.index} className={`group grid gap-6 border-b border-white/10 bg-gradient-to-r ${layer.tone} px-1 py-8 transition hover:px-5 sm:grid-cols-[70px_0.8fr_1.2fr]`}><span className="font-mono text-xs text-violet-300">{layer.index}</span><h3 className="text-2xl font-medium text-white">{layer.title}</h3><p className="max-w-md text-sm leading-7 text-slate-400">{layer.text}</p></article>)}</div></div></section>

      <section className="mx-auto grid max-w-7xl gap-10 px-5 py-20 sm:px-8 lg:grid-cols-[1.1fr_0.9fr] lg:px-10 lg:py-32" id="workflow"><div className="relative min-h-[480px] overflow-hidden border border-white/10 bg-[#101019] p-5 sm:p-8"><div className="absolute inset-0 bg-[radial-gradient(circle_at_75%_20%,rgba(192,38,211,0.22),transparent_35%)]" /><div className="relative"><div className="flex items-center justify-between border-b border-white/10 pb-5"><span className="text-sm font-semibold">Today at Kora</span><span className="font-mono text-xs text-emerald-300">● synced</span></div><div className="mt-8 grid gap-4 sm:grid-cols-2"><div className="border border-violet-300/20 bg-violet-500/10 p-5"><span className="text-xs text-slate-400">Cash position</span><strong className="mt-5 block text-4xl text-white">NGN 4.8m</strong><span className="mt-2 block text-xs text-emerald-300">↑ 12.4% from last month</span></div><div className="border border-white/10 bg-white/[0.03] p-5"><span className="text-xs text-slate-400">Open loops</span><strong className="mt-5 block text-4xl text-white">08</strong><span className="mt-2 block text-xs text-fuchsia-300">3 need your attention</span></div></div><div className="mt-5 border border-white/10 bg-white/[0.03] p-5"><div className="flex justify-between text-xs text-slate-400"><span>Operating momentum</span><span>72%</span></div><div className="mt-4 h-2 bg-white/10"><div className="h-full w-[72%] bg-gradient-to-r from-violet-500 to-fuchsia-400" /></div><div className="mt-8 space-y-4 text-sm"><p className="flex justify-between border-b border-white/10 pb-3"><span className="text-slate-300">Invoice follow-up sequence</span><span className="text-emerald-300">Ready</span></p><p className="flex justify-between"><span className="text-slate-300">Team workload review</span><span className="text-violet-200">Today</span></p></div></div></div></div><div className="flex flex-col justify-center"><p className="text-[0.68rem] uppercase tracking-[0.24em] text-violet-300">From activity to action</p><h2 className="mt-5 text-4xl font-semibold leading-tight text-white sm:text-6xl">Less hunting. More knowing.</h2><p className="mt-7 max-w-lg text-base leading-8 text-slate-400">Kora gives operators a calm, current picture of what is happening and where the next decision lives. No invented numbers. No black-box confidence. Just the business you are actually running.</p><Link href="/auth?mode=signup" className="mt-8 w-fit rounded-full border border-violet-300/50 px-5 py-3 text-sm text-violet-100 transition hover:bg-violet-500/15">See your operating picture ↗</Link></div></section>

      <section className="border-y border-white/10 bg-[#0a0a11]" id="operators"><div className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-10 lg:py-28"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="text-[0.68rem] uppercase tracking-[0.24em] text-fuchsia-300">Built around real work</p><h2 className="mt-5 max-w-2xl text-4xl font-semibold leading-tight text-white sm:text-6xl">A system people can trust with the details.</h2></div><p className="max-w-xs text-sm leading-6 text-slate-400">For owners, managers, and teams who need the same truth without the same job title.</p></div><div className="mt-16 grid gap-px bg-white/10 md:grid-cols-3">{proofPoints.map(([title, text]) => <article key={title} className="bg-[#0a0a11] p-7 sm:p-9"><span className="text-2xl text-fuchsia-300">✦</span><h3 className="mt-16 text-xl font-medium text-white">{title}</h3><p className="mt-4 text-sm leading-7 text-slate-400">{text}</p></article>)}</div></div></section>

      <section className="relative mx-auto max-w-7xl px-5 py-24 text-center sm:px-8 lg:px-10 lg:py-36"><div className="absolute left-1/2 top-1/2 h-72 w-72 -translate-x-1/2 -translate-y-1/2 rounded-full bg-fuchsia-600/10 blur-3xl" /><div className="relative"><p className="text-[0.68rem] uppercase tracking-[0.24em] text-violet-300">Start with the signal</p><h2 className="mx-auto mt-6 max-w-4xl text-5xl font-semibold leading-[0.95] text-white sm:text-7xl">The next clear decision is already in your business.</h2><Link href="/auth?mode=signup" className="mt-9 inline-block rounded-full bg-white px-7 py-4 text-sm font-semibold text-[#08080f] transition hover:bg-violet-100">Create a Kora workspace ↗</Link></div></section>

      <footer className="border-t border-white/10 bg-[#08080f]"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-14 sm:px-8 lg:grid-cols-[1.3fr_0.7fr_0.7fr_0.7fr] lg:px-10"><div><Link href="/" className="flex items-center gap-3"><span className="logo-mark">K</span><span className="text-lg font-semibold">Kora</span></Link><p className="mt-5 max-w-xs text-sm leading-6 text-slate-500">A living operating picture for businesses doing real work.</p></div><div><p className="text-xs uppercase tracking-[0.2em] text-slate-500">Explore</p><div className="mt-5 space-y-3 text-sm text-slate-300"><a href="#system" className="block hover:text-white">The system</a><a href="#workflow" className="block hover:text-white">How it works</a><a href="#operators" className="block hover:text-white">For operators</a></div></div><div><p className="text-xs uppercase tracking-[0.2em] text-slate-500">Account</p><div className="mt-5 space-y-3 text-sm text-slate-300"><Link href="/auth?mode=signin" className="block hover:text-white">Sign in</Link><Link href="/auth?mode=signup" className="block hover:text-white">Create workspace</Link><Link href="/dashboard" className="block hover:text-white">Dashboard</Link></div></div><div><p className="text-xs uppercase tracking-[0.2em] text-slate-500">Connect</p><p className="mt-5 text-sm leading-6 text-slate-400">For product questions and partnerships<br /><a href="mailto:hello@kora.ng" className="text-violet-200 hover:text-white">hello@kora.ng</a></p></div></div><div className="mx-auto flex max-w-7xl flex-col justify-between gap-3 border-t border-white/10 px-5 py-5 text-xs text-slate-600 sm:flex-row sm:px-8 lg:px-10"><span>© 2026 Kora. All rights reserved.</span><span>Privacy · Terms · Status</span></div></footer>
    </main>
  );
}
